### ISSUE TITLE
[main FE] 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by dev-sena** [codestates-seb/seb41_main_030#1]
## Description
nav, footer 구현
<br />

## Todo
nav
1. [x] 기본적인 nav 구현
2. [x] 로그인 전 - 커뮤니티, 전문가, 로그인, 회원가입 
3. [x] 로그인 후 - 커뮤니티, 전문가, 로그아웃, 마이페이지

footer
1. [x] footer 구현
<br />

## Duration
ex) 1d
